name: Auto Merge Approved PRs

on:
  schedule:
    - cron: '0 */2 * * *'  # Every 2 hours
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  auto-merge-prs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check for running workflows
        id: check_workflows
        run: |
          # Get all running workflows except this one
          running_workflows=$(gh run list --status in_progress --json workflowName,name --jq '.[].name' | grep -v "Auto Merge Approved PRs" | wc -l)
          echo "running_workflows=$running_workflows" >> $GITHUB_OUTPUT
          
          if [ "$running_workflows" -gt 0 ]; then
            echo "Found $running_workflows running workflows. Exiting to avoid conflicts."
            echo "should_continue=false" >> $GITHUB_OUTPUT
          else
            echo "No other workflows running. Proceeding with auto-merge."
            echo "should_continue=true" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get organization info
        id: org_info
        if: steps.check_workflows.outputs.should_continue == 'true'
        run: |
          repo_info=$(gh repo view --json owner)
          org_name=$(echo "$repo_info" | jq -r '.owner.login')
          echo "org_name=$org_name" >> $GITHUB_OUTPUT
          
          # Get all organization members with admin role
          echo "Getting organization admins..."
          admins=$(gh api "orgs/$org_name/members?role=admin" --jq '.[].login' | tr '\n' ' ')
          echo "org_admins=$admins" >> $GITHUB_OUTPUT
          echo "Organization admins: $admins"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Find and merge approved PRs
        if: steps.check_workflows.outputs.should_continue == 'true'
        run: |
          org_admins="${{ steps.org_info.outputs.org_admins }}"
          merged_count=0
          max_merges=2
          
          echo "Organization admins: $org_admins"
          echo "Looking for PRs with exact comment 'bot merge please' from any org admin..."
          
          # Get all open PRs
          prs=$(gh pr list --state open --json number,title,url)
          
          if [ "$prs" = "[]" ]; then
            echo "No open PRs found."
            exit 0
          fi
          
          # Process each PR
          echo "$prs" | jq -r '.[] | @base64' | while IFS= read -r pr_data; do
            if [ "$merged_count" -ge "$max_merges" ]; then
              echo "Reached maximum merge limit ($max_merges). Stopping."
              break
            fi
            
            pr_info=$(echo "$pr_data" | base64 --decode)
            pr_number=$(echo "$pr_info" | jq -r '.number')
            pr_title=$(echo "$pr_info" | jq -r '.title')
            pr_url=$(echo "$pr_info" | jq -r '.url')
            
            echo "Checking PR #$pr_number: $pr_title"
            
            # Get all comments for this PR
            comments=$(gh pr view "$pr_number" --json comments --jq '.comments[]')
            
            # Print all comment authors for debugging
            echo "Comments in PR #$pr_number:"
            echo "$comments" | jq -r '"  - Author: " + .author.login + " | Comment: " + (.body | split("\n")[0] | .[0:100])'
            
            # Check if any comment from an org admin contains exactly "bot merge please"
            has_merge_comment=false
            echo "$comments" | jq -r '.author.login + "|" + .body' | while IFS='|' read -r comment_author comment_body; do
              # Check if the comment author is in the list of org admins
              if echo "$org_admins" | grep -wq "$comment_author"; then
                # Check for exact match "bot merge please" (case-insensitive)
                if echo "$comment_body" | grep -iExq "bot merge please"; then
                  echo "Found exact 'bot merge please' comment from org admin '$comment_author' in PR #$pr_number"
                  echo "true" > /tmp/has_merge_comment_$pr_number
                  break
                fi
              fi
            done
            
            # Check if merge comment was found
            if [ -f "/tmp/has_merge_comment_$pr_number" ]; then
              has_merge_comment=true
            fi
            
            if [ "$has_merge_comment" = true ]; then
              echo "Attempting to merge PR #$pr_number..."
              
              # Check if PR can be merged
              pr_mergeable=$(gh pr view "$pr_number" --json mergeable --jq '.mergeable')
              
              if [ "$pr_mergeable" = "MERGEABLE" ]; then
                # Merge the PR
                if gh pr merge "$pr_number" --merge --delete-branch; then
                  echo "Successfully merged PR #$pr_number: $pr_title"
                  merged_count=$((merged_count + 1))
                else
                  echo "Failed to merge PR #$pr_number: $pr_title"
                fi
              else
                echo "PR #$pr_number is not mergeable (status: $pr_mergeable)"
              fi
            else
              echo "No exact 'bot merge please' comment found from any org admin in PR #$pr_number"
            fi
            
            # Clean up temp file
            rm -f "/tmp/has_merge_comment_$pr_number"
          done
          
          echo "Auto-merge process completed. Merged $merged_count PRs."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
